[platformio]
default_envs = esp32_real

[env]
framework = arduino
platform = espressif32
board = esp32dev
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

[env:esp32_real]
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Iinclude
extra_scripts = scripts/run_post_upload.py
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    ArduinoJson
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/adafruit/Adafruit_LSM6DS.git
    https://github.com/adafruit/Adafruit_LIS3MDL.git
    https://github.com/adafruit/Adafruit_Sensor.git
    BluetoothSerial
